### ISSUE TITLE
Would it be possible to tweak timers to still work when defeated?

### ISSUE THREAD

**Issue by grekker** [QuitarHero/Hero-Timers#2]
Noticed on Sabetha the other day when I was calling cannons for people that when I was defeated I lost my timers. The squad was still fighting so it was a tough moment but we recovered.

I know there are reset conditions that make it possible for the timer to automatically stop and restart when the fight restarts, is there any nuance here that could be used to tune it more specifically to cover this scenario where the fight is ongoing but you are dead?

Thanks for making this pack, by the way. Amazingly useful.

**Comment by QuitarHero** [comment]
I'll change the timers so they work as you describe for Sabetha for today's release, as Sabetha's timers are one of the two main reasons why people use these timers, but I'll leave the others as they are.

Having a timer begin and end with combat is both immersive (for what it can be), but more importantly better design. It's unfortunate that being dead in-game makes you effectively out-of-combat, but mumble-link only supports knowing combat state and not alive/downed/defeated states (as that is useful knowledge for botters, among other things), and the main developer of it is no longer working at ArenaNet. As such, the choices are either to always have a timer running no matter the combat state, and continue post-fight until you leave the combat area, or to have it end when combat ends, which includes being defeated.

As a note, timers are only effective within their specified range, so even with this change, if you for example get knocked off by a Bandit Thug while waiting for a Sapper Bomb at a cannon, accidentily dodge off the platform as a kiter, or attempt to use the updraft if you come back from a cannon at an un-opportune time and fall to the bottom, the timer will not function and the timers will no longer display.
Also with this change, the timer will only begin when you enter the specified area and *not* by combat start, meaning that if you either do not use my [Marker Pack](https://github.com/QuitarHero/Heros-Marker-Pack) to know how close to the boss on the bridge you can go before you start the fight, or are simply late entering the platform, the timers will not be as accurate as they have been, and will instead be delayed by how long it takes for you or anyone else to enter the platform.
