### ISSUE TITLE
Timers Update V0.3.12: Timers Load Error

### ISSUE THREAD

**Issue by Hayato2846** [QuitarHero/Hero-Timers#3]
After updating Timers Module, updating Hero Timers pack and restarting Blish I still have following issue:

Multiple timers get an Load Error: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true

Logs:
11:26:26.5722 | ERROR | Blish_HUD.Modules.Module | Sabetha the Saboteur
All Cannons Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Sabetha the Saboteur
Cannon 1/3 Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Sabetha the Saboteur
Cannon 1/3 (skip south) Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Sabetha the Saboteur
Cannon 2/4 Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Sabetha the Saboteur
Cannon 2/4 (skip east) Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Slothasor
Mushrooms & Slub Spawns Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Bandit Trio
Global Mechanics Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6119 | ERROR | Blish_HUD.Modules.Module | Matthias
Global Mechanics Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6203 | ERROR | Blish_HUD.Modules.Module | Matthias
Global Mechanics (with markers) Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6203 | ERROR | Blish_HUD.Modules.Module | Matthias
Global Mechanics (with trails) Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6203 | ERROR | Blish_HUD.Modules.Module | Xera
Global Mechanics Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6342 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
Kite Strategy: Agony #1 Timer parsing failure: raid.cairn.kite.agony1: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6342 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
Kite Strategy: Agony #2 Timer parsing failure: raid.cairn.kite.agony2: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6342 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
Kite Strategy: Agony #3 Timer parsing failure: raid.cairn.kite.agony3: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6342 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
Kite Strategy: Agony #4 Timer parsing failure: raid.cairn.kite.agony4: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6570 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
No-Kite Strategy: Agony #3 Timer parsing failure: raid.cairn.nokite.agony3: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6655 | ERROR | Blish_HUD.Modules.Module | Cairn the Indomitable
No-Kite Strategy: Agony #4 Timer parsing failure: raid.cairn.nokite.agony4: At least one of requireEntry and requireDeparture must be set to true
11:26:26.6655 | ERROR | Blish_HUD.Modules.Module | Mursaat Overseer
Dispel Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6655 | ERROR | Blish_HUD.Modules.Module | Mursaat Overseer
Challenge Mode Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.6655 | ERROR | Blish_HUD.Modules.Module | Samarog
Spear Spawns Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7290 | ERROR | Blish_HUD.Modules.Module | Deimos
Unnatural Signet Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7290 | ERROR | Blish_HUD.Modules.Module | Deimos
Oil Timings Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7290 | ERROR | Blish_HUD.Modules.Module | Soulless Horror
Pushing Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7662 | ERROR | Blish_HUD.Modules.Module | Dhuum
Green #2 (kiter) Timer parsing failure: raid.dhuum.green2.kiter: At least one of requireEntry and requireDeparture must be set to true
11:26:26.7746 | ERROR | Blish_HUD.Modules.Module | Twin Largos
Nikare's Breakbar Timings Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7746 | ERROR | Blish_HUD.Modules.Module | Twin Largos
Kenut's Breakbar Timings Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7746 | ERROR | Blish_HUD.Modules.Module | Qadim
Lamp 1/2/3 Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true
11:26:26.7746 | ERROR | Blish_HUD.Modules.Module | Qadim
Lamp #3 Timer parsing failure: Reset trigger invalid - At least one of requireEntry and requireDeparture must be set to true

**Comment by QuitarHero** [comment]
This looks like the module failed to remove a previous version of, `Hero-Timers.zip`.
What you can do is go to: `/Documents/Guild Wars 2/addons/blishhud/timers` and remove it if it's there, then Restart Blish HUD or reload the Timer Module.
If it's not there, then for consistency you can remove all files in the `/timers` directory, Restart Blish HUD / Timer Module, then re-download from the module prompt.

Let me know if there are any other issues.

**Comment by Hayato2846** [comment]
Yeah you're right. Right now Timers Module is not able to unzip the new files. After deleting everything in timers folder, downloading the pack again and clicking on 'Continue' nothing happens. I manually unzipped the files, restarted Blish and everything works fine.

Thanks!
